# Generated by Django 5.0.6 on 2024-05-21 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BankInterface', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BankInterface.account')),
            ],
        ),
    ]
