# Generated by Django 5.0.6 on 2024-05-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterface',
            name='ATM_NUMBER',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinterface',
            name='PIN',
            field=models.IntegerField(default=3468),
            preserve_default=False,
        ),
    ]
