# Generated by Django 5.0.6 on 2024-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0002_userinterface_atm_number_userinterface_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterface',
            name='ATM_NUMBER',
        ),
        migrations.RemoveField(
            model_name='userinterface',
            name='NAME',
        ),
        migrations.RemoveField(
            model_name='userinterface',
            name='PIN',
        ),
        migrations.AddField(
            model_name='userinterface',
            name='card_number',
            field=models.CharField(default=6087149810567718, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinterface',
            name='pin',
            field=models.CharField(default=1289, max_length=4),
            preserve_default=False,
        ),
    ]
